# Generated by Django 3.2.1 on 2021-05-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='subject',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='phone',
            new_name='telefono',
        ),
    ]
